// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from MyCSharpNativeModule
using MyCSharpNativeModule;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from MyCSharpNativeModule
            packageProviders.Add(new MyCSharpNativeModule.ReactPackageProvider());
        }
    }
}
